INSERT INTO PRODUCT(name, price, description) VALUES ('Café',12.75, 'Rancheiro');
INSERT INTO PRODUCT(name, price, description) VALUES ('Pão de Queijo',7.99, 'Artesanal');
INSERT INTO PRODUCT(name, price, description) VALUES ('Leite',4.79, 'Integral');
INSERT INTO PRODUCT(name, price, description) VALUES ('Iogurte',15.97, 'Morango');
INSERT INTO PRODUCT(name, price, description) VALUES ('Queijo',6, 'Bovino');
INSERT INTO PRODUCT(name, price, description) VALUES ('Suco',20, 'Morango');
INSERT INTO PRODUCT(name, price, description) VALUES ('Suco ',15.97, 'Laranja');
INSERT INTO PRODUCT(name, price, description) VALUES ('Rosquinha',12, 'Cobertura côco');
INSERT INTO PRODUCT(name, price, description) VALUES ('Chocolate Quente',40, '40% de cacau');
INSERT INTO PRODUCT(name, price, description) VALUES ('Bolo',25.90, 'Sabor mandioca');
INSERT INTO PRODUCT(name, price, description) VALUES ('Cappucinno',5, 'Cremoso');
INSERT INTO PRODUCT(name, price, description) VALUES ('Pão Mandi',12.99, '1 Kg');
INSERT INTO PRODUCT(name, price, description) VALUES ('Pão de Milho',18.79, '1Kg');
INSERT INTO PRODUCT(name, price, description) VALUES ('Enroladinho',15.97, 'Queijo');
INSERT INTO PRODUCT(name, price, description) VALUES ('Patê',7.99, 'Batata');
INSERT INTO PRODUCT(name, price, description) VALUES ('Tapioca',20, 'Mandioca');
INSERT INTO PRODUCT(name, price, description) VALUES ('Milharina ',15.97, 'De doce');
INSERT INTO PRODUCT(name, price, description) VALUES ('Polenta',12, 'Ao leite');
INSERT INTO PRODUCT(name, price, description) VALUES ('Cuzcuz',40, 'Ao queijo');
INSERT INTO PRODUCT(name, price, description) VALUES ('Ovos',12, 'Fritos com cebola de cabeça');
INSERT INTO PRODUCT(name, price, description) VALUES ('Paçoca',8.72, 'Amendoím');
INSERT INTO PRODUCT(name, price, description) VALUES ('Peta ',7.75, 'Polvilho');
INSERT INTO PRODUCT(name, price, description) VALUES ('Maçã',3.56, 'Verde');
INSERT INTO PRODUCT(name, price, description) VALUES ('Maçã',10, 'Vermelha');
INSERT INTO PRODUCT(name, price, description) VALUES ('Banana',12.75, 'Prata');